### ISSUE TITLE
Support for "Multi-Platform-Jars"

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi#520]
With [JEP 412: Foreign Function & Memory API](https://openjdk.java.net/jeps/412) JNI in its classic form will not be required anymore and much hassle will hopefully vanish.

Still this reveals a new problem, that if for different platform different libs are used then different bindings would be required. Even though there are several ways to mitigate this, OSGi already supports the concept of platform specific native libraries.

Therefore, similar to Multi-Release-jars, it would be good if an OSGi framework would support loading class alternatives based on the running os/architecture for example we have a basic class `A.class` and then there is `OSGI-INF/win32/x64/A.class` this one will be loaded instead of the `A.class`, for example Eclipse-SWT could massively benefit from such a feature.

**Comment by bjhargrave** [comment]
There is [JEP 434: Foreign Function & Memory API (Second Preview)](https://openjdk.org/jeps/434) in JDK 20. So the design is still fluid and we should keep an eye on it.

That said, fragments are already used for this sort of thing. It is not pretty but basically works. Adding multi-release jar support for platforms would create its own set of new issues. People misspell folder names, etc. I don't think FFM adds anything new to the native code issue over its current state with JNI. So the same (current) techniques used for JNI can still be used for FFM. That is, platform-specific fragments or bundles.

**Comment by laeubi** [comment]
> That said, fragments are already used for this sort of thing. It is not pretty but basically works.

Its not pretty and it does not scale well ... it just adds a lot of management effort both for build and runtime, e.g. I need a way to deploy the "right" fragment, and it does not work to override classes from a host (as the host is searched before fragments. All this can (again) be solved with even more fragments, more indirection but at the bottom line I just want one class loaded depending on the used os/arch...

For sure this won't be something one uses very often but if it is needed its a real headache and FFM won't solve the issue that e.g. on linux you want to use gtk and on windows win32 and on mac cocoa as the native code binding.

**Comment by bjhargrave** [comment]
From our discussion in the spec project call yesterday, I would suggest instead of defining a new multi-platform directory convention that we modify the `Bundle-NativeCode` header (see https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#framework.module-loading.native.code.libraries) such that the `nativecode` symbol is expanded to allow it to represent an embedded native library (current behavior) or an embedded path which is to be prefixed to the bundle's `Bundle-ClassPath` (BCP). So one could say:

```
Bundle-NativeCode: OSGI-INF/win32/x64/;osname=win32;processor=x86-64
```

The trailing slash in `OSGI-INF/win32/x64/` indicates the `nativecode` symbol represents a BCP prefix entry rather than a native library for `System.loadLibrary`.

This proposal allows all the normal, existing processing for `Bundle-NativeCode` to function (de-aliasing, resolving, etc.) and allows tools to understand the meaning of the `nativecode` symbol to verify the path exists in the bundle and to process any classes therein.

**Comment by tjwatson** [comment]
What about code that is platform agnostic?  Could that still exist in the default location of `.`?  Or does it have to be copied into each supported native folder?  Would this extra directory specified in the `Bundle-NativeCode` header (e.g. `OSGI-INF/win32/x64/`) be an additional directory which is checked first before using the root directory?

```
Bundle-ClassPath: ., lib/nativeStuff.jar
Bundle-NativeCode: OSGI-INF/win32/x64/;osname=win32;processor=x86-64
```

Where do we search for `.`?  Only in `OSGI-INF/win32/x64/`?  What about `lib/nativeStuff.jar`?

What happens if the `Bundle-NativeCode` clause has `*` at the end, specifying it is optional?  Does it fall back to looking up the classpath elements with no prefix?

**Comment by bjhargrave** [comment]
The path is prefixed to BCP. So for your example, if the native match happens for `osname=win32;processor=x86-64`, the effective BCP is `OSGI-INF/win32/x64/,.,lib/nativeStuff.jar`.

**Comment by tjwatson** [comment]
OK, the restriction is that the prepend classpath elements have to be directories.  I'm fine with that.

So the intention is to prepend zero or more directory classpath elements to the bundle class path and the native paths can have a mix of directory and file elements:
```
Bundle-NativeCode: 
 OSGI-INF/native1/;
 OSGI-INF/libs/mylib1.dll;
 OSGI-INF/native2/;
 OSGI-INF/libs/mylib1.dll;
 osname=win32;processor=x86-64
```
Anything ending in `/` is considered to be a prepend element to BCP everything else is a library like usual.

**Comment by HannesWell** [comment]
Since it raised in another discussion (https://github.com/eclipse-platform/eclipse.platform.swt/discussions/497#discussioncomment-4402479):
Do you know a way to achieve a similar behavior without OSGi? AFAIK there is no standard way in 'plain' java to have 'multi-platform' jars similar like multi-platform jars.

**Comment by laeubi** [comment]
> Since it raised in another discussion ([eclipse-platform/eclipse.platform.swt#497 (reply in thread)](https://github.com/eclipse-platform/eclipse.platform.swt/discussions/497#discussioncomment-4402479)): Do you know a way to achieve a similar behavior without OSGi? AFAIK there is no standard way in 'plain' java to have 'multi-platform' jars similar like multi-platform jars.

Currently it is neither possible with OSGi nor with "plain" java but maybe OSGi this time can be a source for bring this to Java as a JEP.

Actually the code used in equinox to get the os/arch is nothing specific to OSGi ... it is just a mapping from some vendor specific strings to a "unified" form, but assuming you are a JDK vendor, you actually should know the os/arch your native binary is compiled for, so it would be just a constant expression and much easier to archive. So actually from a JKDs POV it would be more a matter of define some osname one can use and archnames ... then the concept of a MR-Jar can easily extended to such code as well.

**Comment by jzy3d** [comment]
I am myself having similar questions on an [OpenGL binding API written with JEP-412](https://gitlab.com/jzy3d/panama-gl).

For now, I rather discussed [code design](https://mail.openjdk.org/pipermail/panama-dev/2022-December/018184.html) than module design, when willing to offer a common interface to several potential hardware.

When thinking about jar deployment, I was thinking of 
* Marking target **OS/Versions** (macOS, windows, linux) in the implementation jar names (see Bindings + Natives jar [in this design sheet](https://gitlab.com/jzy3d/panama-gl/-/blob/main/doc/PanamaGL-Design.md)).
* Marking the JDK version they were compiled with through [Maven Classifiers](https://www.baeldung.com/maven-artifact-classifiers). Panama is still moving and I already got stuffs in JDK17 not compatible with JDK 19, so maybe I'd like to maintain compatibilities to several versions.

My thinking is that the Java classpath get everything need in the classpath, and that it is the framework responsability (here : mine) to find the appropriate (Open)**GL** implementation that fit the user requirements (OSGI is probably not relevant for helping me find the approrpiate jar for a given {GPU+CPU+JDK} user config).

Would this be compatible to an OSGI approach?
  
How would you recommend me to OSGIfy PanamaGL?

**Comment by laeubi** [comment]
> * Marking the JDK version they were compiled with through [Maven Classifiers](https://www.baeldung.com/maven-artifact-classifiers). Panama is still moving and I already got stuffs in JDK17 not compatible with JDK 19, so maybe I'd like to maintain compatibilities to several versions.

I think a Multi-Release-Jar would be more appropriate than a different artifact for different jvm-versions

> My thinking is that the Java classpath should get everything available in the classpath (all hardware related optional jars), and that it is the framework responsability (here : mine) to find the appropriate (Open)**GL** implementation that fits the user requirements

That is how many code is working today, the problem always is to find the "right" choice and it always require some levels of indirection that complicate code. And if it works for your library, still your users will facing the same problem (that's the same with SWT where fpr example OLE is only available for the windows portion of the code).

> Would this be compatible to an OSGI approach?

This just depends on how you search your code, but in general you are not forced to use the OSGi aproach it just makes your life often easier :-)

> How would you recommend me to OSGIfy PanamaGL?

Some usual approach would include I think at the moment it is a bit hard to decide until it is clear how it is supposed to work. But looking at the current design I would assume that one having `panama-gl-core` being the bundle users reference (e.g. through import-package) and having the `wrapper-xxx` being a fragment to the `panama-gl-core` bundle.

With the discussed approach here, there will be other options, but I'm not sure they fit well in a "classic" deployment scenarion, thats why I still think the initial proposal with having some standard folder structure like `OSGI-INF/win32/x64/A.class` would be more appropriate as it better maps to the classic deployment model as well, even though currently the OSGi spec currently work in a way that is more flexible (e.g allows many different names).

To prevent from ambiguities maybe one can enhance this with just one fragment e.g. `platform`  then code has two choices:

1. `META-INF/versions/<version>` --> JDK version specific classes
2. `META-INF/platforms/<os>/<arch>` --> platform specific classes
3. `META-INF/platforms/<os>/<arch>/<version>` --> platform specific classes that are for a specific version

Is anyone familiar with creating new JEPs? It might be good to have similar discussions/request there as well?

**Comment by laeubi** [comment]
Still an issue...

**Comment by laeubi** [comment]
Still an issue....
